// Reads items from an HTML document with CSS selectors.
import * as cheerio from 'cheerio';
import type { CheerioAPI } from 'cheerio';
import type { Element } from 'domhandler';
import { validHref } from '../../shared/detect.js';
import type { FieldKey, FieldRule, FieldRules } from '../../shared/types.js';
import { parseDate } from './dates.js';
import { absolutize, backgroundImageUrl, cleanInline, cleanMultiline, isElement, nodeText, pickImageSource } from './html.js';

export interface RawItem {
  title: string | null;
  link: string | null;
  content: string | null;
  contentIsHtml: boolean;
  date: number | null;
  image: string | null;
  author: string | null;
  guid?: string | null;
  /** Content generated by Glaneur itself (page watcher diffs): kept without sanitizing. */
  trusted?: boolean;
  found: Partial<Record<FieldKey, boolean>>;
}

export interface PageMeta {
  title: string | null;
  description: string | null;
  iconUrl: string | null;
  image: string | null;
  lang: string | null;
  baseUrl: string;
}

export const FIELD_LABELS: Record<FieldKey, string> = {
  title: 'Titre',
  link: 'Lien',
  description: 'Contenu',
  date: 'Date',
  image: 'Image',
  author: 'Auteur',
};

export function loadHtml(html: string): CheerioAPI {
  return cheerio.load(html);
}

export function pageMeta($: CheerioAPI, pageUrl: string): PageMeta {
  const baseUrl = absolutize($('base[href]').first().attr('href'), pageUrl) ?? pageUrl;
  const metaContent = (selector: string) => cleanInline($(selector).first().attr('content')) || null;
  const title = cleanInline($('head > title, title').first().text()) || metaContent('meta[property="og:title"]');

  let icon: { href: string; score: number } | null = null;
  for (const el of $('link[rel][href]').toArray()) {
    const rel = (el.attribs.rel ?? '').toLowerCase();
    if (!/(^|\s)(icon|apple-touch-icon)(\s|$)/.test(rel)) continue;
    const size = parseInt((el.attribs.sizes ?? '').split('x')[0], 10);
    let score = Number.isFinite(size) ? size : rel.includes('apple') ? 180 : 32;
    if (score > 256) score = 256 - (score - 256) / 100;
    if (/svg/.test(el.attribs.type ?? '') || /\.svg(\?|$)/.test(el.attribs.href)) score = 200;
    if (!icon || score > icon.score) icon = { href: el.attribs.href, score };
  }
  let iconUrl = icon ? absolutize(icon.href, baseUrl) : null;
  if (!iconUrl) {
    try {
      iconUrl = new URL('/favicon.ico', pageUrl).href;
    } catch {
      iconUrl = null;
    }
  }

  return {
    title: title || null,
    description: metaContent('meta[name="description"]') ?? metaContent('meta[property="og:description"]'),
    iconUrl,
    image: absolutize(metaContent('meta[property="og:image"]'), baseUrl),
    lang: cleanInline($('html').attr('lang')) || null,
    baseUrl,
  };
}

function defaultAttr(key: FieldKey): string {
  switch (key) {
    case 'link':
      return 'href';
    case 'image':
      return 'src';
    case 'date':
      return 'datetime';
    case 'description':
      return 'html';
    default:
      return 'text';
  }
}

function applyRegex(value: string, pattern: string): string | null {
  try {
    const m = new RegExp(pattern, 'i').exec(value);
    return m ? (m[1] ?? m[0]) : null;
  } catch {
    return value;
  }
}

function findTarget($: CheerioAPI, item: Element, rule: FieldRule, key: FieldKey): Element | null {
  const selector = rule.selector.trim();
  if (selector === ':scope') return item;
  try {
    return $(item).find(selector).toArray().find(isElement) ?? null;
  } catch {
    throw new Error(`Sélecteur invalide pour « ${FIELD_LABELS[key]} » : ${selector}`);
  }
}

function readHref($: CheerioAPI, el: Element): string | null {
  if (validHref(el.attribs.href ?? null)) return el.attribs.href;
  const inner = $(el).find('a[href]').toArray().find((a) => isElement(a) && validHref(a.attribs.href ?? null));
  if (inner) return inner.attribs.href;
  for (let p = el.parent; p && isElement(p); p = p.parent) {
    if (p.name === 'a' && validHref(p.attribs.href ?? null)) return p.attribs.href;
  }
  return el.attribs['data-href'] ?? el.attribs['data-url'] ?? null;
}

function readImage($: CheerioAPI, el: Element): string | null {
  const img = el.name === 'img' ? el : ($(el).find('img').toArray().find(isElement) ?? null);
  if (img) {
    const src = pickImageSource((n) => img.attribs[n]);
    if (src) return src;
  }
  const source = $(el).find('source[srcset]').first().attr('srcset');
  if (source) return source.split(/[\s,]+/)[0] || null;
  const bg = backgroundImageUrl(el.attribs.style);
  if (bg) return bg;
  for (const child of $(el).find('[style*="url("]').toArray()) {
    const url = isElement(child) ? backgroundImageUrl(child.attribs.style) : null;
    if (url) return url;
  }
  return el.attribs.poster ?? el.attribs.content ?? el.attribs['data-bg'] ?? null;
}

function readDate(el: Element, lang: string | null): number | null {
  const candidates = [
    el.attribs.datetime,
    el.attribs.content,
    el.attribs['data-timestamp'],
    el.attribs['data-time'],
    el.attribs['data-date'],
    cleanInline(nodeText(el)),
    el.attribs.title,
  ];
  for (const c of candidates) {
    const t = parseDate(c, { lang });
    if (t) return t;
  }
  return null;
}

interface FieldValue {
  text: string | null;
  date?: number | null;
}

function readField($: CheerioAPI, item: Element, rule: FieldRule, key: FieldKey, lang: string | null): FieldValue {
  const el = findTarget($, item, rule, key);
  if (!el) return { text: null };
  const attr = (rule.attr ?? '').trim() || defaultAttr(key);
  let value: string | null;
  let date: number | null | undefined;
  switch (attr) {
    case 'text':
      value = key === 'description' ? cleanMultiline(nodeText(el)) : cleanInline(nodeText(el));
      break;
    case 'html':
      value = $(el).html()?.trim() ?? null;
      break;
    case 'href':
      value = readHref($, el);
      break;
    case 'src':
      value = readImage($, el);
      break;
    case 'datetime':
      value = el.attribs.datetime ?? cleanInline(nodeText(el));
      if (key === 'date' && !rule.regex) date = readDate(el, lang);
      break;
    case 'bg':
      value = backgroundImageUrl(el.attribs.style);
      break;
    default:
      value = el.attribs[attr] ?? null;
  }
  if (value && rule.regex) value = applyRegex(value, rule.regex);
  value = value?.trim() || null;
  if (key === 'date' && date === undefined) date = parseDate(value, { lang });
  return { text: value, date };
}

function autoLink($: CheerioAPI, item: Element, titleEl: Element | null): string | null {
  if (titleEl) {
    const href = readHref($, titleEl);
    if (href) return href;
  }
  if (item.name === 'a' && validHref(item.attribs.href ?? null)) return item.attribs.href;
  const links = $(item).find('a[href]').toArray().filter((a) => isElement(a) && validHref(a.attribs.href ?? null));
  const inHeading = links.find((a) => $(a).closest('h1,h2,h3,h4,h5,h6').length > 0 || $(a).find('h1,h2,h3,h4,h5,h6').length > 0);
  return (inHeading ?? links[0])?.attribs.href ?? null;
}

function autoTitle($: CheerioAPI, item: Element): string | null {
  const heading = $(item).find('h1,h2,h3,h4,h5,h6').toArray().find(isElement);
  if (heading) {
    const t = cleanInline(nodeText(heading));
    if (t) return t;
  }
  let best = '';
  for (const a of $(item).find('a[href]').toArray()) {
    const t = cleanInline(nodeText(a));
    if (t.length > best.length) best = t;
  }
  return best || null;
}

export function extractHtmlItems(
  $: CheerioAPI,
  source: { itemSelector: string; fields: FieldRules },
  lang: string | null,
  limit = 300,
): RawItem[] {
  const selector = source.itemSelector.trim();
  if (!selector) return [];
  let nodes: Element[];
  try {
    nodes = $(selector).toArray().filter(isElement);
  } catch {
    throw new Error(`Sélecteur d’élément invalide : ${selector}`);
  }
  return nodes.slice(0, limit).map((item) => {
    const found: RawItem['found'] = {};
    const get = (key: FieldKey): FieldValue => {
      const rule = source.fields[key];
      if (!rule?.selector?.trim()) return { text: null };
      const v = readField($, item, rule, key, lang);
      if (v.text || v.date) found[key] = true;
      return v;
    };
    // Without a title rule, a content rule gives a better title (derived later) than the longest link.
    const title = get('title').text ?? (source.fields.title?.selector || source.fields.description?.selector ? null : autoTitle($, item));
    // Without a link rule, the link that carries the title is the article link (not a vote or share link).
    const titleRule = source.fields.title;
    const titleEl = titleRule?.selector?.trim() ? findTarget($, item, titleRule, 'title') : null;
    const link = get('link').text ?? autoLink($, item, titleEl);
    const description = get('description');
    const date = get('date');
    return {
      title,
      link,
      content: description.text,
      contentIsHtml: ((source.fields.description?.attr ?? '') || 'html') === 'html',
      date: date.date ?? null,
      image: get('image').text,
      author: get('author').text,
      found,
    };
  });
}
